language: python
python:
  - "3.10"
# command to install dependencies
install:
  - pip install pygame==2.5.1
# command to run tests
script:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk python -m pygame.tests
os: osx
osx_image: xcode9.4
