language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pygame==2.5.1
# command to run tests
script:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk python -m pygame.tests
os: osx

# https://docs.travis-ci.com/user/reference/osx
# 10.13, 10.12, 10.11
osx_image: 
  - xcode10.1
  - xcode9.2
  - xcode8
